import { config } from "../../config.js";

export const COACH_BASE_WEEKLY_REQUESTS = config.COACH_BASE_WEEKLY_REQUESTS;

export const COACH_REFERRAL_BONUS_REQUESTS =
  config.COACH_REFERRAL_BONUS_REQUESTS;

export const COACH_MAX_REFERRALS = config.COACH_MAX_REFERRALS;

export const DEFAULT_REFERRAL_CODE_LENGTH = config.REFERRAL_CODE_LENGTH;
