export const GYM_MUSCLE_LIST = Object.freeze([
  "Chest",
  "Back",
  "Shoulders",
  "Biceps",
  "Triceps",
  "Forearms",
  "Core",
  "Abdominals",
  "Obliques",
  "Lower Back",
  "Glutes",
  "Quadriceps",
  "Hamstrings",
  "Calves",
  "Hip Flexors",
  "Trapezius",
  "Latissimus Dorsi",
  "Rhomboids",
  "Rear Deltoids",
]);
