services:
  frontend:
    image: ishnoopy/fit-check-frontend:latest
    container_name: frontend
    environment:
      - API_URL=${API_URL}
    expose:
      - "3000"
    depends_on:
      backend:
        condition: service_healthy

  backend:
    image: ishnoopy/fit-check-backend:latest
    container_name: backend
    environment:
      - FRONTEND_URL=${FRONTEND_URL}
      - DB_URL=${DB_URL}
      - JWT_SECRET=${JWT_SECRET}
      - BACKEND_PORT=${BACKEND_PORT}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_REDIRECT_URI=${GOOGLE_REDIRECT_URI}
      - AWS_REGION=${AWS_REGION}
      - AWS_S3_BUCKET_NAME=${AWS_S3_BUCKET_NAME}
      - AWS_ACCESS_KEY_ID=${MINIO_ROOT_USER}
      - AWS_SECRET_ACCESS_KEY=${MINIO_ROOT_PASSWORD}
      - MINIO_ENDPOINT=${MINIO_ENDPOINT}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - REDIS_URL=${REDIS_URL}
    volumes:
      - backend_logs:/app/logs
    expose:
      - "4000"
    depends_on:
      minio:
        condition: service_healthy
    healthcheck:
      test:
        ["CMD-SHELL", "wget -qO- http://localhost:4000/api/health || exit 1"]
      interval: 30s
      timeout: 3s
      retries: 5
      start_period: 15s

  minio:
    image: minio/minio:latest
    container_name: minio
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    expose:
      - "9000"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5

  createbuckets:
    image: minio/mc:latest
    container_name: minio-init
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      AWS_S3_BUCKET_NAME: ${AWS_S3_BUCKET_NAME}
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      mc alias set local http://minio:9000 $$MINIO_ROOT_USER $$MINIO_ROOT_PASSWORD;
      mc mb --ignore-existing local/$$AWS_S3_BUCKET_NAME;
      exit 0;
      "

  caddy:
    image: caddy:2
    container_name: caddy
    restart: unless-stopped
    depends_on:
      frontend:
        condition: service_started
    dns:
      - 8.8.8.8
      - 1.1.1.1
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config

volumes:
  minio_data:
  caddy_data:
  caddy_config:
  backend_logs:
